version: "3.9"

#---------- List Docker services ----------
services:

  #---------- Node Exporter parameters ----------
  node_exporter:
     build:
       context : ./requirements/bonus/node_exporter/.
     image: node_exporter
     container_name: node_exporter
     restart: always
     networks:
       - inception

  #---------- MariaDB parameters ----------
  mariadb:
     build:
       context : ./requirements/mariadb/.
     image: mariadb
     container_name: mariadb
     restart: always
     volumes:
       - db_volume:/var/lib/mysql/
     env_file :
       - .env
     networks:
       - inception

  #---------- Redis parameters ----------
  redis:
     build:
       context : ./requirements/bonus/redis/.
     image: redis
     container_name: redis
     restart: always
     networks:
       - inception
     env_file :
       - .env

  #---------- Wordpress parameters ----------
  wordpress:
     build :
       context : ./requirements/wordpress/.
     image : wordpress
     container_name: wordpress
     restart: always
     volumes :
       - nginx_volume:/var/www/html
     env_file :
       - .env
     networks:
       - inception
     depends_on :
       - mariadb
       - redis

  #---------- NGINX parameters ----------
  nginx:
     build:
       context : ./requirements/nginx/.
     image: nginx
     container_name: nginx
     ports:
       - "443:443"
     restart: always
     volumes:
       - nginx_volume:/var/www/html/
     networks:
       - inception
     depends_on :
       - wordpress

  #---------- Adminer parameters ----------
  adminer:
     build:
       context : ./requirements/bonus/adminer/.
     image: adminer
     container_name: adminer
     restart: always
     volumes:
       - db_volume:/var/lib/mysql
       - nginx_volume:/var/www/html/
     networks:
       - inception
     depends_on :
       - mariadb

  #---------- FTP parameters ----------
  ftp:
     build:
       context : ./requirements/bonus/ftp/.
     image: ftp
     container_name: ftp
     restart: always
     ports:
       - "21:21"
     volumes:
       - nginx_volume:/var/www/html/
     networks:
       - inception
     depends_on:
       - wordpress
     env_file :
       - .env

  #---------- Prometheus parameters ----------
  prometheus:
     build:
       context : ./requirements/bonus/prometheus/.
     image: prometheus
     container_name: prometheus
     restart: always
     networks:
       - inception
     depends_on:
       - node_exporter

  #---------- Grafana parameters ----------
  grafana:
     build:
       context : ./requirements/bonus/grafana/.
     image: grafana
     container_name: grafana
     restart: always
     ports:
       - "3000:3000"
     networks:
       - inception
     env_file :
       - .env
     depends_on:
       - prometheus

#---------- List Docker volumes ----------
volumes:

  #---------- MariaDB volume ----------
  db_volume:
     driver: local
     driver_opts:
       type: none
       device: ${USER_HOME}/data/db_volume
       o: bind
  
  #---------- Wordpress volume ----------
  nginx_volume:
     driver: local
     driver_opts:
       type: none
       device: ${USER_HOME}/data/nginx_volume
       o: bind
      
#---------- List Docker networks ----------
networks:

  #---------- Simple networks ----------
  inception:
     driver: bridge